### ISSUE TITLE
Error in scClustViz::getExpr(inD, assayType) : assayType '' not found.

### ISSUE THREAD

**Issue by FarzanT** [BaderLab/CCInx#2]
Hello,
I wanted to use the `BuildGeneStatList()` function, like below:
```
# Prepare for CCInx
gene_stats <- BuildGeneStatList(inD = sc_obj, cl = sc_obj$hpca_cell_name,
                                assayType = "", exponent = 2, pseudocount = 1)
```
But I am encountered with the following error:
```
Error in scClustViz::getExpr(inD, assayType) : assayType '' not found.
  The following assay data are available in this object:
  RNA, integrated
```
When I provide `"RNA"` as the `assayType`, I encounter the following error:
```
Error in scClustViz::getExpr(inD, assayType) : 
  argument "assaySlot" is missing, with no default
```
I am using the latest Seurat version:
```
> sc_obj@version
[1] ‘3.1.0’
```
I've also installed the latest scClustViz from Github:
```
# devtools::install_github('Baderlab/scClustViz')
```

Please let me know if I am doing anything incorrectly.

Thank you,
Farzan

**Comment by innesbre** [comment]
Thanks for noticing this.  A recent update to scClustViz caused this bug.  Just pushed a fix, so if you update scClustViz to v1.3.1 by running `devtools::install_github("BaderLab/scClustViz")` this should be fixed.
Also, it looks like you've done a data integration in your Seurat object.  You probably want to use the integrated data for your downstream analysis, rather than the original data in the "RNA" slot.  You can check what assay object Seurat is using by default in your object by using the DefaultAssay(my_seurat_object) command.
